# Generated by Django 5.1.3 on 2024-12-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authpage", "0002_user_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                ("rating", models.PositiveSmallIntegerField(verbose_name="оценка")),
                ("date", models.DateField(auto_now=True, verbose_name="дата")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_feedbacks",
                        related_query_name="my_feedbacks",
                        to="authpage.user",
                    ),
                ),
                (
                    "seller_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        related_query_name="feedbacks",
                        to="authpage.user",
                    ),
                ),
            ],
        ),
    ]
