# Generated by Django 5.1.3 on 2025-02-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
