# Generated by Django 5.1.3 on 2025-02-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.CharField(max_length=255, verbose_name="цена"),
        ),
    ]
