# Generated by Django 5.1.3 on 2025-02-15 15:34

import authpage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=None, verbose_name="описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True, upload_to="uploads/", verbose_name="изображение"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.CharField(
                default=None, max_length=255, verbose_name="местоположение"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="phone_number",
            field=models.CharField(
                default=None,
                max_length=255,
                validators=[authpage.validators.PhoneNumberValidator()],
                verbose_name="номер телефона",
            ),
            preserve_default=False,
        ),
    ]
