# Generated by Django 5.1.3 on 2025-02-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_category_region_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                related_query_name="products",
                to="catalog.category",
            ),
            preserve_default=False,
        ),
    ]
