# Generated by Django 5.1.3 on 2025-02-21 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="city",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                related_query_name="products",
                to="catalog.city",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="region",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                related_query_name="products",
                to="catalog.region",
            ),
            preserve_default=False,
        ),
    ]
