# Generated by Django 5.1.3 on 2025-02-21 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_city_product_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="email",
            field=models.EmailField(
                default=None,
                max_length=255,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="email",
            ),
            preserve_default=False,
        ),
    ]
