# Generated by Django 5.1.3 on 2025-02-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "категория", "verbose_name_plural": "категории"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "город", "verbose_name_plural": "города"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "продукт", "verbose_name_plural": "продукты"},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "регион", "verbose_name_plural": "регионы"},
        ),
    ]
