# Generated by Django 5.1.3 on 2025-02-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_galleryimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="location",
        ),
    ]
