# Generated by Django 5.1.3 on 2025-02-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_remove_product_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
