# Generated by Django 5.1.3 on 2025-03-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_remove_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.PositiveIntegerField(verbose_name="цена"),
        ),
    ]
