# Generated by Django 5.1.3 on 2024-11-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginpage", "0002_alter_user_email_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="secret", max_length=255),
        ),
    ]
