# Generated by Django 5.1.7 on 2025-04-11 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, 'Invalid rating value'), django.core.validators.MaxValueValidator(5, 'Invalid rating value')], verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
