# Generated by Django 5.1.7 on 2025-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
