# Generated by Django 5.1.3 on 2024-12-12 15:29

import authpage.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="имя пользователя"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=255,
                        validators=[authpage.validators.PhoneNumberValidator()],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.EmailValidator(
                                "Введите валидную почту"
                            )
                        ],
                        verbose_name="Почта",
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="пароль")),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
