# Generated by Django 5.1.3 on 2024-12-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(default="", null=True, verbose_name="О себе"),
        ),
    ]
