# Generated by Django 5.1.3 on 2024-12-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authpage", "0002_user_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                default=None, max_length=255, verbose_name="имя пользователя"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(
                default=None, max_length=255, verbose_name="фамилия пользователя"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="хэндл пользователя"
            ),
        ),
    ]
