# Generated by Django 5.1.3 on 2025-01-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authpage", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True, upload_to="uploads/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
