# Generated by Django 5.1.3 on 2025-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authpage", "0005_user_image_alter_user_email"),
        ("catalog", "0005_product_description_product_image_product_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="liked_products",
            field=models.ManyToManyField(
                related_name="liked_by",
                related_query_name="liked_by",
                to="catalog.product",
                verbose_name="Понравившиеся товары",
            ),
        ),
    ]
