# Generated by Django 5.1.7 on 2025-04-10 15:22

import authpage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0006_user_liked_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True, validators=[authpage.validators.PhoneNumberValidator()], verbose_name='Номер телефона'),
        ),
    ]
